### ISSUE TITLE
README suggestion

### ISSUE THREAD

**Issue by Lemez** [sunabozu/ukrainian-phonetic-keylayout-mac#2]
Hi,

I'm on Catalina 10.15.7...

Two small updates for the README:

1. copy the contents of the unzipped folder to Library/Keyboard Layouts (not the master folder)
2. Keyboard is available under Others -> Ukrainian Phonetic (not under 'Ukrainian')

Thank you for this.

**Comment by sunabozu** [comment]
Thanks

[6e387df](https://github.com/sunabozu/ukrainian-phonetic-keylayout-mac/commit/6e387dfe131faa50bb8f4801fefaed0fd5510f1b)
